dependencies:
- name: demo-thorntail-102100
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.9
- name: demo102100
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: maven-simplest
  repository: http://jenkins-x-chartmuseum:8080
  version: 3.5.4
- name: starter-kotlin
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
